config/routes.rb
MusicApp::Application.routes.draw do
  resources :users
  resource :sessions
  resources :bands do
    resources :albums, :except => :show
  end

  resources :albums

  resources :tracks
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :title, :album_type
  validates :album_type, :presence => true, :inclusion => %w(S L) #studio/live
  validates :band_id, :presence => true
  validates :title, :presence => true

  belongs_to(
    :band,
    :class_name => "Band",
    :foreign_key => :band_id,
    :primary_key => :id
  )

  # has_many(
#     :tracks,
#     :class_name => "Track",
#     :foreign_key => :album_id,
#     :primary_key => :id,
#     :dependent => :destroy
#   )
end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name

  has_many(
    :albums,
    :class_name => "Album",
    :foreign_key => :band_id,
    :primary_key => :id,
    :dependent => :destroy
  )

  has_many :tracks, :through => :albums#, :source => :track
end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title, :album_id, :track_type
  validates :track_type, :inclusion => %w(B R) #bonus/regular

  belongs_to(
    :album,
    :class_name => "Album",
    :foreign_key => :album_id,
    :primary_key => :id
  )
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password_digest, :secret, :session_token
  attr_reader :secret
  validates :secret, :length => { :minimum => 6 }, :allow_nil => true
  before_validation :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(email, secret)
    user = User.find_by_email(email)
    if user
      user.is_password?(secret) ? user : nil
    end
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end


  def secret=(secret)
    @secret = secret
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @bands = Band.all
    @albums = Album.all
  end

  def new
    @album = Album.new
    @bands = Band.all
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      flash[:notice] = "Album successfully saved"
      redirect_to bands_url
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to new_album_url
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(params[:band])
    if @band.save
      flash[:notice] = "Band successfully added"
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:secret]
    )
    if @user.nil?
      flash[:notice] = "Email not in databse"
      redirect_to new_sessions_url
    elsif @user.save
      @user.reset_session_token!
      session[:session_token] = @user.session_token
      flash[:notice] = "You have successfully logged in"
      redirect_to user_url(@user)
    else
      #this part doesn't work properly
      flash[:notice] = "Invalid Login"
      redirect_to new_sessions_url
    end

  end

  def destroy
    session[:session_token] = nil if self.logged_in?
    redirect_to new_sessions_url
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @albums = Album.all
    @track = Track.new
  end

  def create
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:session_token] = @user.session_token
      flash[:notice] = "User Creation Successful"
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
  end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  attr_accessor :current_user

  def current_user
    return nil if session[:session_token].nil?
    User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    self.current_user.session_token == session[:session_token]
  end

  def log_in_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<% if params["band_id"].nil? %>
  <% @albums.each do |album| %>
    <%= album.title %>
  <% end %>
<% else %>

  <% @bands.each do |band| %>
    <% if band.id == params["band_id"].to_i %>
      <% band.albums.each do |album| %>
        <%= album.title %>
      <% end %>
    <% end %>

  <% end %>
<% end %>

app/views/albums/new.html.erb
<h1>Add Album</h1>

<form action="<%= albums_url %>" method="post">
  <label for="select band">Select Band</label>
  <br>
  <select name="album[band_id]" id="band_name">
    <% @bands.each do |band| %>
      <option value="<%= band.id %>"><%= band.name %></option>
    <% end %>
  </select>
  <br>
  <br>
  <label for="album title">Album Title</label>
  <br>
  <input type="text" name="album[title]" id="album_title">
  <br>
  <br>
  Select album type
  <br>
  <input type="radio" name="album[album_type]" value="L">
  <label for="album_type_live">Live</label>
  <br>
  <input type="radio" name="album[album_type]" value="S">
  <label for="album_type_studio">Studio</label>
  <br>

  <br>
  <br>
  <input type="submit" value="Add album">
</form>

app/views/bands/new.html.erb
<h1>Add Band</h1>

<form action="<%= bands_url %>" method="post">
  <label>Band Name</label>
  <input type="text" name="band[name]" id="band_name">

  <input type="submit" value="Add band">
</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h3>Albums</h3>
<% @band.albums.each do |album| %>
  <%= album.title %>
  <br>
  <% %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
      <%= error %>
    <% end %>
  <% end %>

  <% if flash[:notice]%>
    <%= flash[:notice] %>
  <% end %>

  <!-- <% if self.current_user %>
    <%= self.current_user.email %>
    <%= button_to "Log Out", sessions_url, :method => :delete %>
  <% else %>
    <%= button_to "Log In", new_sessions_url, :method => :get %>
  <% end %> -->


<%= yield %>

</body>
</html>

app/views/tracks/new.html.erb
<h1>Add Track</h1>

<form action="<%= albums_url %>" method="post">
  <label for="select album">Album</label>
  <br>
  <select name="track[album_id]" id="album_name">
    <% @albums.each do |album| %>
      <option value="<%= album.id %>"><%= album.title %></option>
    <% end %>
  </select>
  <br>
  <br>
  <label for="track_title">Track Title</label>
  <br>
  <input type="text" name="track[title]" id="track_title">
  <br>
  <br>
  <label for="select track">Select Track Type</label>
  <input type="radio" name="track[track_type]" value="B">
  <label for="track_type_bonus">Bonus</label>
  <input type="radio" name="track[track_type]" value="R">
  <label for="track_type_regular">Regular</label>
  <br>
  <label for="Lyrics">Add Lyrics</label>
  <textarea name="track[lyrics]"></textarea>

  <br>
  <br>
  <input type="submit" value="Add track">
</form>

app/views/users/index.html.erb
INDEX

app/views/users/new.html.erb
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
  <label for="email">Email address</label>
  <input type="text" id="email_address" name="user[email]">

  <label for="password">Password</label>
  <input type="password" id="password" name="user[secret]">

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<%= @user.email %>